SELECT DAY('2017/08/25') AS DAY, MONTH('2017/08/25') AS MONTH, YEAR('2017/08/25') AS YEAR;

SELECT COUNT(*) FROM EMPLOYEES WHERE EMPID >= 20;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT NAME, SUM(SALARY_COMPONENTS) FROM EMPLOYEES GROUP BY NAME HAVING SUM(SALARY_COMPONENTS) >= 150000;

SELECT ORDER_ID, ORDER_DATE FROM ORDERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE COUNTRY = 'INDIA');

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMPLOYEE_NAME, DEPARTMENTS.DEPARTMENT_NAME FROM EMPLOYEES FULL OUTER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMPLOYEE_NAME, DEPARTMENTS.DEPARTMENT_NAME FROM EMPLOYEES RIGHT OUTER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

SELECT EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.EMPLOYEE_NAME, DEPARTMENTS.DEPARTMENT_NAME FROM EMPLOYEES LEFT OUTER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
