SELECT ProductID, SUM(Quantity) AS TotalQuantity FROM Orders GROUP BY ProductID;
SELECT * FROM EMPLOYEES WHERE SALARY = (SELECT DISTINCT(SALARY) FROM EMPLOYEES ORDER BY SALARY DESC LIMIT 1,1);
SELECT CustomerID, SUM(Quantity) AS TotalQuantity FROM Orders WHERE ProductID = 12345 AND OrderDate > '2020-11-11' GROUP BY CustomerID ORDER BY TotalQuantity DESC;
