## SQL Queries Set 3

```sql
1. Retrieve Customers Who Have Not Placed Any Orders:
   SELECT * FROM CUSTOMERS
   WHERE CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM ORDERS);

2. Find Employees Who Have Been Working for More Than 5 Years:
   SELECT * FROM EMPLOYEES
   WHERE JOINING_DATE <= DATEADD(YEAR, -5, GETDATE());

3. Identify Products That Have Never Been Ordered:
   SELECT * FROM PRODUCTS
   WHERE PRODUCT_ID NOT IN (SELECT DISTINCT PRODUCT_ID FROM ORDER_DETAILS);

4. Calculate Total Sales for Each Product Category:
   SELECT C.CATEGORY_NAME, SUM(OD.QUANTITY * OD.UNIT_PRICE) AS TOTAL_SALES
   FROM PRODUCTS P
   JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
   JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
   GROUP BY C.CATEGORY_NAME;

5. Retrieve Employees Who Are Managers (Have Employees Reporting to Them):
   SELECT * FROM EMPLOYEES
   WHERE EMPLOYEE_ID IN (SELECT DISTINCT MANAGER_ID FROM EMPLOYEES);
