## SQL Queries Set 4

```sql
1. Retrieve Products That Have Exceeded Their Stock Limit:
   SELECT * FROM PRODUCTS
   WHERE STOCK_QUANTITY > STOCK_LIMIT;

2. Find Customers Who Have Spent More Than $1000 in Total:
   SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, SUM(OD.QUANTITY * OD.UNIT_PRICE) AS TOTAL_SPENT
   FROM CUSTOMERS C
   JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
   JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
   GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
   HAVING SUM(OD.QUANTITY * OD.UNIT_PRICE) > 1000;

3. Identify Employees Who Have the Highest Salary in Each Department:
   SELECT E.* FROM EMPLOYEES E
   JOIN (
       SELECT DEPARTMENT_ID, MAX(SALARY) AS MAX_SALARY
       FROM EMPLOYEES
       GROUP BY DEPARTMENT_ID
   ) M ON E.DEPARTMENT_ID = M.DEPARTMENT_ID AND E.SALARY = M.MAX_SALARY;

4. Retrieve Orders Placed Within the Last 30 Days:
   SELECT * FROM ORDERS
   WHERE ORDER_DATE >= DATEADD(DAY, -30, GETDATE());

5. Calculate the Average Order Value:
   SELECT AVG(OD.QUANTITY * OD.UNIT_PRICE) AS AVERAGE_ORDER_VALUE
   FROM ORDER_DETAILS OD;
